# Generated by Django 5.2.3 on 2025-06-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills (e.g., Python, Django, JavaScript)'),
        ),
    ]
