# Generated by Django 5.2.3 on 2025-06-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hr_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
