# Generated by Django 5.2.3 on 2025-06-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companyprofile_hr_email_companyprofile_hr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], default='Online', max_length=20),
        ),
    ]
