# Generated by Django 5.2.3 on 2025-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interviewschedule_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='additional_instructions',
            field=models.TextField(blank=True, help_text='Any additional instructions for the candidate.'),
        ),
    ]
